name: Build

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Ctarget-feature=+sse4.2 -Cinstrument-coverage"
  RUSTDOCFLAGS: "-Ctarget-feature=+sse4.2"
  LLVM_PROFILE_FILE: "CityHash_sys-%p-%m.profraw"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          include:
            - os: macos-latest
              target: x86_64-apple-darwin
            - os: ubuntu-latest
              target: x86_64-unknown-linux-gnu
            - os: windows-latest
              target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        run:  rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Rust
      run: |
          rustup toolchain add nightly --component llvm-tools-preview
          rustup override set nightly
          cargo install grcov
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Generate coverage
      run: |
              grcov $(find . -name "CityHash_sys-*.profraw" -print) \
              --branch \
              --ignore-not-existing \
              --binary-path ./target/debug/ \
              -s . \
              -t lcov \
              --ignore "/*" \
              --ignore build.rs \
              -o lcov.info
    - name: Upload report to codecov
      uses: codecov/codecov-action@v2

